<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class Sakarsian extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ['nama' => 'Fiezha Hasby Ari Widana', 'nim' => 'H2401241127', 'email' => 'ezahasby@apps.ipb.ac.id', 'kode' => 'A1'],
            ['nama' => 'Fatma Dwi Hasanah', 'nim' => 'I3401241034', 'email' => 'fatmadwihasanah@apps.ipb.ac.id', 'kode' => 'A2'],
            ['nama' => 'Tedy Kusuma Hidayat', 'nim' => 'E1401241022', 'email' => 'tedykusuma@apps.ipb.ac.id', 'kode' => 'A3'],
            ['nama' => 'Arifatu Dzikra', 'nim' => 'M0401241003', 'email' => 'stat24arifatu@apps.ipb.ac.id', 'kode' => 'A4'],
            ['nama' => 'Dewi Ayu Lestari', 'nim' => 'G7401241024', 'email' => '61dewiayulestari@apps.ipb.ac.id', 'kode' => 'A5'],
            ['nama' => 'Nur Fadillah', 'nim' => 'D3401241081', 'email' => 'dillaanur@apps.ipb.ac.id', 'kode' => 'A6'],
            ['nama' => 'Elegi Gita Manuella', 'nim' => 'I3401241076', 'email' => 'manuellaelegi@apps.ipb.ac.id', 'kode' => 'B1'],
            ['nama' => 'Danya Christabel Novelina Silalahi', 'nim' => 'F2401241025', 'email' => 'danyachristabel@apps.ipb.ac.id', 'kode' => 'B2'],
            ['nama' => 'Naisya Sarwa Nafisah', 'nim' => 'M0404241053', 'email' => 'nainaisya@apps.ipb.ac.id', 'kode' => 'B3'],
            ['nama' => 'Hilal Putranta', 'nim' => 'A3401241053', 'email' => 'hilalputranta@apps.ipb.ac.id', 'kode' => 'B4'],
            ['nama' => 'Fauziyyah Az Zahrah', 'nim' => 'F2401241034', 'email' => 'zhrfauziyyah@apps.ipb.ac.id', 'kode' => 'B9'],
            ['nama' => 'Muhammad Raihan Ridho Ramadhan', 'nim' => 'F4401241064', 'email' => 'mrr_raihan@apps.ipb.ac.id', 'kode' => 'B17'],
            ['nama' => 'Rafael Moza Christopher', 'nim' => 'G2401241078', 'email' => 'elmozachristopher@apps.ipb.ac.id', 'kode' => 'B16'],
            ['nama' => 'Imelda Triyani', 'nim' => 'H1401241095', 'email' => 'imeldatriyani@apps.ipb.ac.id', 'kode' => 'B13'],
            ['nama' => 'Muhamad Rizky Fadillah', 'nim' => 'H2401241046', 'email' => 'rizkyfadillah@apps.ipb.ac.id', 'kode' => 'B6'],
            ['nama' => 'Andhika Arya Ramdhani', 'nim' => 'H3401241003', 'email' => 'andhikaarya@apps.ipb.ac.id', 'kode' => 'B15'],
            ['nama' => 'Aginda Malika Danish Naira', 'nim' => 'I2401241002', 'email' => 'agindamalikadanishnaira@apps.ipb.ac.id', 'kode' => 'B14'],
            ['nama' => 'Devira Yosi Yatsika', 'nim' => 'I2401241055', 'email' => 'devirayatsika@apps.ipb.ac.id', 'kode' => 'B10'],
            ['nama' => 'Muhammad Fernanda Athallah Ar\'rafii', 'nim' => 'I3401241002', 'email' => 'fernandaathallah@apps.ipb.ac.id', 'kode' => 'B8'],
            ['nama' => 'Dimaz Maulana Arby', 'nim' => 'I3401241005', 'email' => 'dimazarby@apps.ipb.ac.id', 'kode' => 'B11'],
            ['nama' => 'Davina Reizka Dara', 'nim' => 'I3401241100', 'email' => 'drzkdara@apps.ipb.ac.id', 'kode' => 'B12'],
            ['nama' => 'Daffa Naufal Fadhlurahman', 'nim' => 'M0402241081', 'email' => 'daffdaffa@apps.ipb.ac.id', 'kode' => 'B18'],
            ['nama' => 'Muhammad Wafi Robbani', 'nim' => 'M0403241013', 'email' => 'wafiirrobbani@apps.ipb.ac.id', 'kode' => 'B5'],
            ['nama' => 'Micko Fahraezi', 'nim' => 'M0403241033', 'email' => 'fahraezimicko@apps.ipb.ac.id', 'kode' => 'B7'],
            ['nama' => 'Muhammad Reza. A', 'nim' => 'A2401241179', 'email' => 'rezaarifianto@apps.ipb.ac.id', 'kode' => 'C1'],
            ['nama' => 'Yusril Muhammad Firdaus', 'nim' => 'I3401241010', 'email' => 'mfyusril@apps.ipb.ac.id', 'kode' => 'C2'],
            ['nama' => 'Gilan Eka El Ginar', 'nim' => 'I3401241145', 'email' => 'gilaneka@apps.ipb.ac.id', 'kode' => 'C3'],
            ['nama' => 'Mahira Delia Arbanty', 'nim' => 'A4401241045', 'email' => 'nauvalrezky@apps.ipb.ac.id', 'kode' => 'C17'],
            ['nama' => 'Khairunnisa Naia Safira', 'nim' => 'E2401241057', 'email' => 'khairunnisanaia@apps.ipb.ac.id', 'kode' => 'C9'],
            ['nama' => 'Tesalonika Lisnawanti Purba', 'nim' => 'E3401241123', 'email' => 'purbatesalonika@apps.ipb.ac.id', 'kode' => 'C5'],
            ['nama' => 'Chatya Putri Dwinata', 'nim' => 'F3401241126', 'email' => 'dwinatachatya@apps.ipb.ac.id', 'kode' => 'C15'],
            ['nama' => 'Dina Chairatul Hasni', 'nim' => 'H2401241019', 'email' => 'thisdina@apps.ipb.ac.id', 'kode' => 'C11'],
            ['nama' => 'Alya Syiffa Maharani', 'nim' => 'H2401241048', 'email' => 'maharanialya@apps.ipb.ac.id', 'kode' => 'C12'],
            ['nama' => 'Zafar Khan Abasi', 'nim' => 'H2401241133', 'email' => 'zafarkhanzafar@apps.ipb.ac.id', 'kode' => 'C16'],
            ['nama' => 'Dini Rahma Putriani', 'nim' => 'H3401241139', 'email' => '06diniirrahma@apps.ipb.ac.id', 'kode' => 'C4'],
            ['nama' => 'Bilqist Azalia Shaqila', 'nim' => 'I2401241017', 'email' => 'bilqistazalia@apps.ipb.ac.id', 'kode' => 'C13'],
            ['nama' => 'Fawwaz Raihan Aziz', 'nim' => 'I2401241097', 'email' => 'fawwazaziz@apps.ipb.ac.id', 'kode' => 'C18'],
            ['nama' => 'M. Rafi Furqon', 'nim' => 'I3401241007', 'email' => 'rafifurqon@apps.ipb.ac.id', 'kode' => 'C8'],
            ['nama' => 'Daffa Sabri Al-Falah', 'nim' => 'I3401241013', 'email' => 'sabrialfalah@apps.ipb.ac.id', 'kode' => 'C6'],
            ['nama' => 'Muhammad Nauval Rezky Dwiananda', 'nim' => 'I3401241023', 'email' => 'nauvalrezky@apps.ipb.ac.id', 'kode' => 'C14'],
            ['nama' => 'Hafizh Nasywa Krisnawala', 'nim' => 'I3401241133', 'email' => 'hafizhkrisnawala@apps.ipb.ac.id', 'kode' => 'C7'],
            ['nama' => 'Muhammad Reza Rahman', 'nim' => 'L1401241009', 'email' => 'rhmnreza@apps.ipb.ac.id', 'kode' => 'C10'],
            ['nama' => 'Pascal Arya Nugroho', 'nim' => 'M0401241078', 'email' => 'pascalpascal@apps.ipb.ac.id', 'kode' => 'E1'],
            ['nama' => 'Salma Rana Mudrikah', 'nim' => 'A4401241060', 'email' => 'salmarana@apps.ipb.ac.id', 'kode' => 'E2'],
            ['nama' => 'Kezia Oktaviani', 'nim' => 'H2401241033', 'email' => 'keziaoktaviani@apps.ipb.ac.id', 'kode' => 'E3'],
            ['nama' => 'Farhan Ibrahim Budiarto', 'nim' => 'A1401241048', 'email' => 'budiartofarhan@apps.ipb.ac.id', 'kode' => 'E15'],
            ['nama' => 'Balqis Humaira', 'nim' => 'C1401241054', 'email' => 'humairabalqis@apps.ipb.ac.id', 'kode' => 'E10'],
            ['nama' => 'Noval Abdurrahman', 'nim' => 'C4401241016', 'email' => 'novalabdurrahman@apps.ipb.ac.id', 'kode' => 'E13'],
            ['nama' => 'Rizki Hazmi Putra', 'nim' => 'D1401241004', 'email' => 'hazmirizki@apps.ipb.ac.id', 'kode' => 'E4'],
            ['nama' => 'Riqqa Aulya Maharani', 'nim' => 'D1401241088', 'email' => 'rlymaharani@apps.ipb.ac.id', 'kode' => 'E6'],
            ['nama' => 'Asya Bianca Jasmine', 'nim' => 'D3401241024', 'email' => 'asyabianca@apps.ipb.ac.id', 'kode' => 'E8'],
            ['nama' => 'Rizky Arkananta Firmana Gunawan', 'nim' => 'E4401241113', 'email' => 'arkanantarizky@apps.ipb.ac.id', 'kode' => 'E5'],
            ['nama' => 'Farrell Malik Al Faizal', 'nim' => 'F1401241108', 'email' => 'farrell.malik@apps.ipb.ac.id', 'kode' => 'E11'],
            ['nama' => 'Fachry Rizqi Amada', 'nim' => 'F3401241067', 'email' => 'amadarizqifachry@apps.ipb.ac.id', 'kode' => 'E18'],
            ['nama' => 'Najwa Nurfa’izah Rhamadhanti', 'nim' => 'G3401241036', 'email' => 'wawaa_najwa@apps.ipb.ac.id', 'kode' => 'E14'],
            ['nama' => 'Muhammad Akmal Harahap', 'nim' => 'G7401241037', 'email' => 'akmalharahap@apps.ipb.ac.id', 'kode' => 'E17'],
            ['nama' => 'Sekarayu Rasyha Ftari Azzalia', 'nim' => 'H1401241043', 'email' => 'sekarayurasyhaftari@apps.ipb.ac.id', 'kode' => 'E12'],
            ['nama' => 'Salman Maliki', 'nim' => 'K1401241066', 'email' => '141105salman@apps.ipb.ac.id', 'kode' => 'E16'],
            ['nama' => 'Nailah Afia Tsabita', 'nim' => 'M0401241023', 'email' => '0304abit_tsabita@apps.ipb.ac.id', 'kode' => 'E9'],
            ['nama' => 'Sangkara Arya Widyatna', 'nim' => 'M0403241136', 'email' => 'sangkaraawidyatna@apps.ipb.ac.id', 'kode' => 'E7'],
            ['nama' => 'Alfath Asqar Tsani', 'nim' => 'M0403241019', 'email' => 'alfathasqar@apps.ipb.ac.id', 'kode' => 'D1'],
            ['nama' => 'Azzahra Kholisa Aura', 'nim' => 'I2401241063', 'email' => 'azzahraaura@apps.ipb.ac.id', 'kode' => 'D2'],
            ['nama' => 'Bradja Putra Jajuli', 'nim' => 'M0401241004', 'email' => 'bradjaapbradja@apps.ipb.ac.id', 'kode' => 'D3'],
            ['nama' => 'Febriananta Rafa Fadilah', 'nim' => 'F2401241006', 'email' => 'febrianantarafa@apps.ipb.ac.id', 'kode' => 'D18'],
            ['nama' => 'Mauliddio Lazuardi Wahyudin', 'nim' => 'F3401241100', 'email' => 'mauliddiowahyudin@apps.ipb.ac.id', 'kode' => 'D7'],
            ['nama' => 'Ashila Air Widiarta', 'nim' => 'G3401241074', 'email' => 'ashilaair@apps.ipb.ac.id', 'kode' => 'D17'],
            ['nama' => 'Adi Pratama', 'nim' => 'M0401241002', 'email' => 'adiipratama@apps.ipb.ac.id', 'kode' => 'D9'],
            ['nama' => 'Fadly Syabani Ardiansyah', 'nim' => 'M0401241006', 'email' => 'fadlysyabani@apps.ipb.ac.id', 'kode' => 'D11'],
            ['nama' => 'Shabrina Nur Izzati', 'nim' => 'M0401241011', 'email' => 'nurizzshabrina@apps.ipb.ac.id', 'kode' => 'D10'],
            ['nama' => 'Najwa Salsabila M.N', 'nim' => 'M0401241016', 'email' => 'najwaaam.n@apps.ipb.ac.id', 'kode' => 'D16'],
            ['nama' => 'Aurelia Fury', 'nim' => 'M0401241029', 'email' => 'fury_22_aurelia@apps.ipb.ac.id', 'kode' => 'D5'],
            ['nama' => 'Qanita Basimah Kurnia', 'nim' => 'M0401241055', 'email' => 'qanitabasimah@apps.ipb.ac.id', 'kode' => 'D15'],
            ['nama' => 'Muhammad Khayruhanif', 'nim' => 'M0401241058', 'email' => 'm.khayruhanif@apps.ipb.ac.id', 'kode' => 'D8'],
            ['nama' => 'Azka Raditya Hafidz', 'nim' => 'M0401241079', 'email' => 'azkaraditya@apps.ipb.ac.id', 'kode' => 'D14'],
            ['nama' => 'Cahya Raras Mitayani', 'nim' => 'M0401241084', 'email' => 'ayambebekraras@apps.ipb.ac.id', 'kode' => 'D13'],
            ['nama' => 'Fitria Angelita Delvi', 'nim' => 'M0401241104', 'email' => 'angelitadelvi@apps.ipb.ac.id', 'kode' => 'D12'],
            ['nama' => 'Muhammad Haidar', 'nim' => 'M0403241038', 'email' => 'muhammadhaidar@apps.ipb.ac.id', 'kode' => 'D4'],
            ['nama' => 'Ayubi Fathan', 'nim' => 'M0403241050', 'email' => 'ayubifathan@apps.ipb.ac.id', 'kode' => 'D6'],
            ['nama' => 'Kyla Anggrahita Wahyudin', 'nim' => 'I3401241148', 'email' => 'kylanggrahita@apps.ipb.ac.id', 'kode' => 'I1'],
            ['nama' => 'Azarah Alri', 'nim' => 'F2401241017', 'email' => 'azaraalri@apps.ipb.ac.id', 'kode' => 'I2'],
            ['nama' => 'Delvin Adithya', 'nim' => 'M0403241001', 'email' => 'delvin_adithya@apps.ipb.ac.id', 'kode' => 'I3'],
            ['nama' => 'Reynaldi Christian', 'nim' => 'B1401241004', 'email' => 'reynaldichristian@apps.ipb.ac.id', 'kode' => 'I12'],
            ['nama' => 'Hudzaifah Abdurrahman', 'nim' => 'F3401241095', 'email' => 'hudzaifahabdurrahman@apps.ipb.ac.id', 'kode' => 'I13'],
            ['nama' => 'Vena Herdiana Damayanti', 'nim' => 'F4401241041', 'email' => 'venaherdiana@apps.ipb.ac.id', 'kode' => 'I16'],
            ['nama' => 'George Valentynus Pasaribu', 'nim' => 'G4401241037', 'email' => 'valentynusgeorge@apps.ipb.ac.id', 'kode' => 'I7'],
            ['nama' => 'Ririn Dwi Kumalasari', 'nim' => 'H2401241012', 'email' => 'ririndwi20kumalasari@apps.ipb.ac.id', 'kode' => 'I14'],
            ['nama' => 'Jhonson Prasetio', 'nim' => 'H3401241043', 'email' => 'jhonsonprasetio@apps.ipb.ac.id', 'kode' => 'I11'],
            ['nama' => 'Yogi Syahputra', 'nim' => 'H4401241001', 'email' => 'yogisyahputra@apps.ipb.ac.id', 'kode' => 'I4'],
            ['nama' => 'Nhimas Ayu Kinanthi', 'nim' => 'H4401241024', 'email' => 'nhimaskinanthi@apps.ipb.ac.id', 'kode' => 'I18'],
            ['nama' => 'Auliya Syifa’a Muthmainnah', 'nim' => 'H4401241099', 'email' => 'aulsyifaa@apps.ipb.ac.id', 'kode' => 'I10'],
            ['nama' => 'Alyssa Fidelia Akbar', 'nim' => 'I2401241107', 'email' => 'alyssafidelia@apps.ipb.ac.id', 'kode' => 'I8'],
            ['nama' => 'Gundara W.S', 'nim' => 'I3401241016', 'email' => 'algundara@apps.ipb.ac.id', 'kode' => 'I5'],
            ['nama' => 'Dafina Azzahra Sinambela', 'nim' => 'I3401241020', 'email' => 'dafinaazzahra@apps.ipb.ac.id', 'kode' => 'I15'],
            ['nama' => 'Akmal Maulana Al Sulfi', 'nim' => 'I3401241040', 'email' => 'maulanaakmal@apps.ipb.ac.id', 'kode' => 'I17'],
            ['nama' => 'Nadia Anggita Hardianzah', 'nim' => 'M0404241018', 'email' => 'nadiaanggita@apps.ipb.ac.id', 'kode' => 'I6'],
            ['nama' => 'Zidny Ilman Nafi', 'nim' => 'M0403241068', 'email' => 'zidny26ilmannafi@apps.ipb.ac.id', 'kode' => 'J1'],
            ['nama' => 'Muthia Rahma', 'nim' => 'G0401241007', 'email' => 'muthia12rahma@apps.ipb.ac.id', 'kode' => 'J2'],
            ['nama' => 'Lara Tria Novita', 'nim' => 'M0401241122', 'email' => 'laratria@apps.ipb.ac.id', 'kode' => 'J3'],
            ['nama' => 'Ergoputra Kusuma Sanjaya', 'nim' => 'A3401241030', 'email' => 'ergoputrasanjaya@apps.ipb.ac.id', 'kode' => 'J9'],
            ['nama' => 'Fattah Ahmadi Nejad', 'nim' => 'C2401241081', 'email' => 'fattahnejad@apps.ipb.ac.id', 'kode' => 'J13'],
            ['nama' => 'Izati Minhalina Riyanisa', 'nim' => 'F2401241023', 'email' => 'izatiminhalina@apps.ipb.ac.id', 'kode' => 'J7'],
            ['nama' => 'Jennifer Chelsea Okto Susanto', 'nim' => 'F2401241048', 'email' => 'jenniferchelsea@apps.ipb.ac.id', 'kode' => 'J12'],
            ['nama' => 'Zahra Dini Khiesa', 'nim' => 'G4401241049', 'email' => 'khiesazahra@apps.ipb.ac.id', 'kode' => 'J6'],
            ['nama' => 'Syifa Khairunissa', 'nim' => 'G7401241007', 'email' => 'nissasyifa@apps.ipb.ac.id', 'kode' => 'J18'],
            ['nama' => 'M. Alfath Al Johari', 'nim' => 'H2401241050', 'email' => 'alfathaljohari@apps.ipb.ac.id', 'kode' => 'J10'],
            ['nama' => 'Hanania Isyqiya Mulyana', 'nim' => 'H5401241028', 'email' => 'hana.mulyana@apps.ipb.ac.id', 'kode' => 'J16'],
            ['nama' => 'Arib Nurfayyadh', 'nim' => 'H5401241088', 'email' => 'fayyadh335arib@apps.ipb.ac.id', 'kode' => 'J5'],
            ['nama' => 'Rike Nur Syafitri', 'nim' => 'I1401241016', 'email' => 'rike30syafitri@apps.ipb.ac.id', 'kode' => 'J14'],
            ['nama' => 'M. Haikal Tabrani', 'nim' => 'M0401241060', 'email' => 'mhaikaltabrani@apps.ipb.ac.id', 'kode' => 'J15'],
            ['nama' => 'Annisa Marwah Saepudin', 'nim' => 'M0401241061', 'email' => 'neezannisa@apps.ipb.ac.id', 'kode' => 'J11'],
            ['nama' => 'Safira Ayu Damayanti', 'nim' => 'M0403241010', 'email' => 'safiraayu71.damayanti@apps.ipb.ac.id', 'kode' => 'J4'],
            ['nama' => 'Daffa Nasywan Islamy', 'nim' => 'M0403241037', 'email' => 'daffanasywan@apps.ipb.ac.id', 'kode' => 'J17'],
            ['nama' => 'Adelia Aisha Akhlaqul Karimah', 'nim' => 'M0404241019', 'email' => 'adeliaaisha@apps.ipb.ac.id', 'kode' => 'J8'],
            ['nama' => 'Rezki Bima Prabaswara', 'nim' => 'K1401241015', 'email' => '9916rezki@apps.ipb.ac.id', 'kode' => 'L1'],
            ['nama' => 'Maleeka Ayesha Nugroho', 'nim' => 'H4401241010', 'email' => 'maleekayesha@apps.ipb.ac.id', 'kode' => 'L2'],
            ['nama' => 'Muhammad Syarief Hidayatullah', 'nim' => 'K1401241181', 'email' => 'mhoahhidayatullah@apps.ipb.ac.id', 'kode' => 'L3'],
            ['nama' => 'Muhamad Daffa Alif Rahman', 'nim' => 'A4401241066', 'email' => 'daffaalifrahman@apps.ipb.ac.id', 'kode' => 'L15'],
            ['nama' => 'Gilbert Alvaro Iglecio Bintang', 'nim' => 'C2401241040', 'email' => 'gilbertbintang@apps.ipb.ac.id', 'kode' => 'L6'],
            ['nama' => 'Belimbing Salima Kamal', 'nim' => 'F2401241018', 'email' => 'belimbingkamal@apps.ipb.ac.id', 'kode' => 'L4'],
            ['nama' => 'Melissa Ayu Prawitaningrum', 'nim' => 'H1401241076', 'email' => 'melissaayu@apps.ipb.ac.id', 'kode' => 'L11'],
            ['nama' => 'Ghina Melanie Taufik', 'nim' => 'H1401241084', 'email' => 'ghinamelanietaufik@apps.ipb.ac.id', 'kode' => 'L7'],
            ['nama' => 'Shabrina Al Alauna Kiandra', 'nim' => 'H2401241129', 'email' => 'kiandrashabrina@apps.ipb.ac.id', 'kode' => 'L16'],
            ['nama' => 'Jo Ann Katrin', 'nim' => 'H3401241014', 'email' => 'joannkatrin@apps.ipb.ac.id', 'kode' => 'L13'],
            ['nama' => 'Muhammad Sandy Fatriawansyah', 'nim' => 'H3401241021', 'email' => 'muhammadsandy@apps.ipb.ac.id', 'kode' => 'L18'],
            ['nama' => 'Hadisti Najmi Alkhonsa', 'nim' => 'K1401241009', 'email' => 'hadistynajmi@apps.ipb.ac.id', 'kode' => 'L10'],
            ['nama' => 'Saskia Aulia Mayeri', 'nim' => 'K1401241011', 'email' => '1456saskia@apps.ipb.ac.id', 'kode' => 'L8'],
            ['nama' => 'Nur Maharani Al Karim', 'nim' => 'K1401241022', 'email' => 'nurmaharanialkarim@apps.ipb.ac.id', 'kode' => 'L9'],
            ['nama' => 'Ardhyasiwi Pradnya Sakti', 'nim' => 'K1401241036', 'email' => 'ardhyasiwipradnya@apps.ipb.ac.id', 'kode' => 'L14'],
            ['nama' => 'Muhamad Hadi Timanta Kaban', 'nim' => 'K1401241126', 'email' => 'muhamadhadi@apps.ipb.ac.id', 'kode' => 'L17'],
            ['nama' => 'Muhammad Sulthan Arkan Mustafa', 'nim' => 'K1401241176', 'email' => 'arkanmustafa@apps.ipb.ac.id', 'kode' => 'L5'],
            ['nama' => 'Muhammad Andika Laksono', 'nim' => 'K1401241245', 'email' => '1508muhammad@apps.ipb.ac.id', 'kode' => 'L12'],
            ['nama' => 'Joseph Farrel', 'nim' => 'G7401241021', 'email' => 'josephfarrel@apps.ipb.ac.id', 'kode' => 'M1'],
            ['nama' => 'Salmaa Maisuun', 'nim' => 'C5401241068', 'email' => 'salmaa.maisuun@apps.ipb.ac.id', 'kode' => 'M2'],
            ['nama' => 'Miftah Rizki Abni Husyairi', 'nim' => 'M0401241088', 'email' => 'rizkimiftah86@apps.ipb.ac.id', 'kode' => 'M3'],
            ['nama' => 'Nadira Naura Nurrachman', 'nim' => 'A4401241081', 'email' => 'nadiranaura@apps.ipb.ac.id', 'kode' => 'M15'],
            ['nama' => 'Miftahul Jannah', 'nim' => 'C5401241004', 'email' => 'miftjannah@apps.ipb.ac.id', 'kode' => 'M10'],
            ['nama' => 'Lutfi Meilano Risuseno', 'nim' => 'C5401241040', 'email' => 'meilanorisuseno@apps.ipb.ac.id', 'kode' => 'M9'],
            ['nama' => 'Edelweiss', 'nim' => 'D2401241121', 'email' => '2005edelweiss@apps.ipb.ac.id', 'kode' => 'M17'],
            ['nama' => 'Asyam Syaddad Farras', 'nim' => 'D3401241074', 'email' => 'asyamsyaddad@apps.ipb.ac.id', 'kode' => 'M11'],
            ['nama' => 'Airra Dzikria Rizatara', 'nim' => 'F2401241091', 'email' => 'rizataraairra@apps.ipb.ac.id', 'kode' => 'M4'],
            ['nama' => 'Fannikha Haeny Dzikriany', 'nim' => 'G0401241031', 'email' => 'fannikhahaen_dzikriany@apps.ipb.ac.id', 'kode' => 'M5'],
            ['nama' => 'Muhamad Rizky Saifi Yusuf', 'nim' => 'H1401241071', 'email' => 'rizkysaifi55yusuf@apps.ipb.ac.id', 'kode' => 'M6'],
            ['nama' => 'Andika Ahmad Nugraha', 'nim' => 'H2401241112', 'email' => 'andikaahmadnugraha@apps.ipb.ac.id', 'kode' => 'M7'],
            ['nama' => 'Moh. Rizky Pratama', 'nim' => 'H4401241109', 'email' => 'rizkyyypratama@apps.ipb.ac.id', 'kode' => 'M13'],
            ['nama' => 'Aqeela Malihah Husna', 'nim' => 'H5401241125', 'email' => 'qlahusna@apps.ipb.ac.id', 'kode' => 'M14'],
            ['nama' => 'Beryl Zorafael Rudi', 'nim' => 'I3401241152', 'email' => 'berylzorafael@apps.ipb.ac.id', 'kode' => 'M12'],
            ['nama' => 'Thoriq Ar Ridfi', 'nim' => 'M0401241057', 'email' => 'arridfithoriq@apps.ipb.ac.id', 'kode' => 'M18'],
            ['nama' => 'Fawwaz Daffa Alvino', 'nim' => 'M0403241053', 'email' => 'fawwazalvino@apps.ipb.ac.id', 'kode' => 'M16'],
            ['nama' => 'Aufa Dzuljalali Wal Ikram', 'nim' => 'M0404241020', 'email' => 'dzuljalaliikram@apps.ipb.ac.id', 'kode' => 'M8'],
            ['nama' => 'Khalifa Alfaiz Wicaksono', 'nim' => 'C5401241030', 'email' => 'khalifalfaizwicaksono@apps.ipb.ac.id', 'kode' => 'F1'],
            ['nama' => 'Lysandra Jasmine Latifah Hendra', 'nim' => 'F1401241095', 'email' => 'lysandrajasmine@apps.ipb.ac.id', 'kode' => 'F2'],
            ['nama' => 'Anes Sulistiawati', 'nim' => 'C2401241017', 'email' => 'sulistiaanes@apps.ipb.ac.id', 'kode' => 'F3'],
            ['nama' => 'Sketsa Smaradhana Bumi', 'nim' => 'A2401241022', 'email' => 'sketsasmaradhana@apps.ipb.ac.id', 'kode' => 'F12'],
            ['nama' => 'Dida Liandaru Zahro', 'nim' => 'C1401241093', 'email' => 'liandarudida269dida@apps.ipb.ac.id', 'kode' => 'F18'],
            ['nama' => 'Adel Muhammad Azka', 'nim' => 'C4401241079', 'email' => 'adelazka@apps.ipb.ac.id', 'kode' => 'F15'],
            ['nama' => 'Tristan Alano Putra Wisnu', 'nim' => 'C5401241808', 'email' => 'alanowisnutristan@apps.ipb.ac.id', 'kode' => 'F17'],
            ['nama' => 'Arifin Muhammad Amin', 'nim' => 'D1401240147', 'email' => 'arifinamin@apps.ipb.ac.id', 'kode' => 'F6'],
            ['nama' => 'Salwa Nasyahta Adzira', 'nim' => 'D1401241007', 'email' => 'salwanasyahta@apps.ipb.ac.id', 'kode' => 'F11'],
            ['nama' => 'Faza Muthiurrohman', 'nim' => 'E1401241031', 'email' => 'muthifaza@apps.ipb.ac.id', 'kode' => 'F5'],
            ['nama' => 'Rafif Syafiq Mahardika', 'nim' => 'F1401241060', 'email' => 'rafif.mahardika@apps.ipb.ac.id', 'kode' => 'F7'],
            ['nama' => 'Juan Andrew', 'nim' => 'F2401241008', 'email' => 'juanandrew@apps.ipb.ac.id', 'kode' => 'F10'],
            ['nama' => 'Ayesha Nashwa Raida Sulthoni', 'nim' => 'F2401241127', 'email' => 'ayeshanashwa@apps.ipb.ac.id', 'kode' => 'F16'],
            ['nama' => 'Muhammad Azkiya Arrayyan', 'nim' => 'F3401241040', 'email' => 'azkiyaarrayyan@apps.ipb.ac.id', 'kode' => 'F4'],
            ['nama' => 'Muhammad Rahmat Dafa', 'nim' => 'F3401241044', 'email' => 'muhrahmatdafa@apps.ipb.ac.id', 'kode' => 'F13'],
            ['nama' => 'Attala Ortzi', 'nim' => 'H3401241115', 'email' => 'attalaortzi@apps.ipb.ac.id', 'kode' => 'F9'],
            ['nama' => 'Tanaya Fathiatul Makiah Hartono', 'nim' => 'I3401241153', 'email' => 'tanayafathmakiah@apps.ipb.ac.id', 'kode' => 'F8'],
            ['nama' => 'Farhan Dzaky Siregar', 'nim' => 'K1401241230', 'email' => 'dzakysiregar@apps.ipb.ac.id', 'kode' => 'F14'],
            ['nama' => 'Radit Anggara', 'nim' => 'I3401241095', 'email' => 'ragadigitanggara@apps.ipb.ac.id', 'kode' => 'K1'],
            ['nama' => 'Lita Thalisa Tiara', 'nim' => 'C2401241069', 'email' => 'tiaralita@apps.ipb.ac.id', 'kode' => 'K2'],
            ['nama' => 'Shaqylla Iqnasia Putri Nugraha', 'nim' => 'M0404241047', 'email' => 'shaqyllaputri@apps.ipb.ac.id', 'kode' => 'K3'],
            ['nama' => 'Reihan Athallah Akbar', 'nim' => 'A2401241140', 'email' => 'athallahreihan@apps.ipb.ac.id', 'kode' => 'K16'],
            ['nama' => 'Diana Ervina Putri', 'nim' => 'C2401241001', 'email' => 'dianaervinaputri@apps.ipb.ac.id', 'kode' => 'K13'],
            ['nama' => 'Lingga Naufal Azura', 'nim' => 'E1401241116', 'email' => 'lingganaufalazura@apps.ipb.ac.id', 'kode' => 'K9'],
            ['nama' => 'Khadeeja Zuhayra Raisa Shazfa Falisha', 'nim' => 'F2401241021', 'email' => 'khadeejazuhayra@apps.ipb.ac.id', 'kode' => 'K18'],
            ['nama' => 'Intan Zabrina', 'nim' => 'F3401241053', 'email' => 'intanzabrina@apps.ipb.ac.id', 'kode' => 'K4'],
            ['nama' => 'Dwi Cindy Hapsari', 'nim' => 'G4401241004', 'email' => 'cindyydwi@apps.ipb.ac.id', 'kode' => 'K7'],
            ['nama' => 'Nauval Mahfudz Muhtadi', 'nim' => 'H1401241007', 'email' => 'nauvalmahfudz@apps.ipb.ac.id', 'kode' => 'K6'],
            ['nama' => 'Virena Harin', 'nim' => 'H1401241073', 'email' => 'virenaharin@apps.ipb.ac.id', 'kode' => 'K8'],
            ['nama' => 'Drajat Fadhlan Rahman', 'nim' => 'H1401241098', 'email' => 'fadhlandrajat@apps.ipb.ac.id', 'kode' => 'K17'],
            ['nama' => 'Nasrullah Ibrahim', 'nim' => 'H2401241010', 'email' => 'nasrullahibrahim@apps.ipb.ac.id', 'kode' => 'K5'],
            ['nama' => 'Pirgiawan Restu Ardani', 'nim' => 'I3401241003', 'email' => 'restuardani@apps.ipb.ac.id', 'kode' => 'K10'],
            ['nama' => 'Anggie Aulya', 'nim' => 'I3401241052', 'email' => 'anggieaulya@apps.ipb.ac.id', 'kode' => 'K15'],
            ['nama' => 'Atiqa Salsabila', 'nim' => 'I3401241138', 'email' => 'atiqasalsabila@apps.ipb.ac.id', 'kode' => 'K12'],
            ['nama' => 'Dzaky Abyan', 'nim' => 'M0403241024', 'email' => 'dzakyabyan@apps.ipb.ac.id', 'kode' => 'K11'],
            ['nama' => 'Mirabel Nasywa Rajendraputri', 'nim' => 'M0403241067', 'email' => 'allaboutzmirabel@apps.ipb.ac.id', 'kode' => 'K14'],
            ['nama' => 'Moura Dwitama', 'nim' => 'M0404241023', 'email' => 'mouradwitama@apps.ipb.ac.id', 'kode' => 'G1'],
            ['nama' => 'Asyaima Putri Maulani Rasyidin', 'nim' => 'D3401241017', 'email' => 'asyaimaputri@apps.ipb.ac.id', 'kode' => 'G2'],
            ['nama' => 'Naura Salsabila Putri Ramadhani', 'nim' => 'M0404241032', 'email' => 'naurasalsabila@apps.ipb.ac.id', 'kode' => 'G3'],
            ['nama' => 'Fathur Syamsy Dhuha', 'nim' => 'C4401241010', 'email' => 'fathursymsydhuha@apps.ipb.ac.id', 'kode' => 'G11'],
            ['nama' => 'Bayu Dwi Aprianto', 'nim' => 'C5401241037', 'email' => 'apriantobayu@apps.ipb.ac.id', 'kode' => 'G9'],
            ['nama' => 'Deva Anisa Nurohmah', 'nim' => 'F1401241086', 'email' => 'devaanisa@apps.ipb.ac.id', 'kode' => 'G18'],
            ['nama' => 'Chelsea Cheryla', 'nim' => 'F2401241086', 'email' => 'chelseacheryla@apps.ipb.ac.id', 'kode' => 'G12'],
            ['nama' => 'Faizah Aura Salsabila', 'nim' => 'F3401241096', 'email' => 'faiz4haura@apps.ipb.ac.id', 'kode' => 'G15'],
            ['nama' => 'Ahmad Faizullah Kianafa Rizwan', 'nim' => 'G3401241052', 'email' => 'ahmadfaizullah@apps.ipb.ac.id', 'kode' => 'G10'],
            ['nama' => 'Alya Azkia Jauza', 'nim' => 'G4401241048', 'email' => 'alyaazkiajauza@apps.ipb.ac.id', 'kode' => 'G13'],
            ['nama' => 'Nadia Sabila', 'nim' => 'H2401241042', 'email' => 'nadiasabila@apps.ipb.ac.id', 'kode' => 'G5'],
            ['nama' => 'Jovan Ali Muzakki', 'nim' => 'H2401241121', 'email' => 'muzakkialijovan@apps.ipb.ac.id', 'kode' => 'G7'],
            ['nama' => 'Reina Amani Wahyudi', 'nim' => 'H3401241075', 'email' => 'reinaamani@apps.ipb.ac.id', 'kode' => 'G6'],
            ['nama' => 'Chelsea Anastacia Dealova', 'nim' => 'K1401241139', 'email' => 'cheydealova@apps.ipb.ac.id', 'kode' => 'G17'],
            ['nama' => 'Aulia Zahra Anindita', 'nim' => 'K1401241175', 'email' => 'auliaanindita@apps.ipb.ac.id', 'kode' => 'G4'],
            ['nama' => 'Naura Girlastin Bachri', 'nim' => 'M0403241124', 'email' => 'nauragirlastin@apps.ipb.ac.id', 'kode' => 'G14'],
            ['nama' => 'Aurelia Zefanya Silalahi', 'nim' => 'M0404241027', 'email' => 'silalahiaurelia@apps.ipb.ac.id', 'kode' => 'G8'],
            ['nama' => 'Fatimah Nur Abdillah', 'nim' => 'M0405241004', 'email' => 'fatimahabdillah@apps.ipb.ac.id', 'kode' => 'G16'],
            ['nama' => 'Okta Fitra Vidian', 'nim' => 'F1401241090', 'email' => 'vidianokta@apps.ipb.ac.id', 'kode' => 'H1'],
            ['nama' => 'Fitri Aulia Nurinsani', 'nim' => 'C5401241075', 'email' => 'fitriaulianurinsani@apps.ipb.ac.id', 'kode' => 'H2'],
            ['nama' => 'Fahri Rahma Akbarsyah', 'nim' => 'H3401241117', 'email' => 'fahrirahmaakbarsyah@apps.ipb.ac.id', 'kode' => 'H3'],
            ['nama' => 'Ayu Kesuma Ningtyas', 'nim' => 'A2401241095', 'email' => 'ayukesumaningtyas@apps.ipb.ac.id', 'kode' => 'H7'],
            ['nama' => 'Amanda Nabilatusyifa', 'nim' => 'A2401241162', 'email' => 'amandasyfaamanda@apps.ipb.ac.id', 'kode' => 'H16'],
            ['nama' => 'Ribka Mandauly Y. Panjaitan', 'nim' => 'C2401241080', 'email' => 'rrmandauly@apps.ipb.ac.id', 'kode' => 'H13'],
            ['nama' => 'Reno Ivanardra Farrel', 'nim' => 'C4401241001', 'email' => 'renoivanardra@apps.ipb.ac.id', 'kode' => 'H10'],
            ['nama' => 'Rivandi Zidane', 'nim' => 'E2401241079', 'email' => 'rivandi2302zidane@apps.ipb.ac.id', 'kode' => 'H8'],
            ['nama' => 'Ishlahuddini Putri', 'nim' => 'E3401241013', 'email' => 'ishlahuddiniputri@apps.ipb.ac.id', 'kode' => 'H18'],
            ['nama' => 'Andika Satria Putra', 'nim' => 'E3401241022', 'email' => 'andikasatria@apps.ipb.ac.id', 'kode' => 'H5'],
            ['nama' => 'Adli Rafiansyah Amin', 'nim' => 'F3401241128', 'email' => 'adlirafiansyah@apps.ipb.ac.id', 'kode' => 'H4'],
            ['nama' => 'Novallin Fajri', 'nim' => 'G3401241046', 'email' => 'novallin100fajri@apps.ipb.ac.id', 'kode' => 'H15'],
            ['nama' => 'Denia Catherine Cecilia Gultom', 'nim' => 'G8401241093', 'email' => 'cathrinedenia@apps.ipb.ac.id', 'kode' => 'H12'],
            ['nama' => 'Pasha Halabi Ikhsanal Haq', 'nim' => 'H3401241124', 'email' => 'pashahalabi@apps.ipb.ac.id', 'kode' => 'H11'],
            ['nama' => 'Alifah Aqela Edra', 'nim' => 'H4401241087', 'email' => 'alifah14alifah@apps.ipb.ac.id', 'kode' => 'H17'],
            ['nama' => 'Aisyah Jazlyn Rizqia', 'nim' => 'H5401241019', 'email' => 'aisyahjazlyn1@apps.ipb.ac.id', 'kode' => 'H6'],
            ['nama' => 'Gusti Karebet Damar Panuluh', 'nim' => 'I1401241021', 'email' => 'gustidamar@apps.ipb.ac.id', 'kode' => 'H9'],
            ['nama' => 'Thaha Abdurrahman', 'nim' => 'K1401241005', 'email' => 'baswedanabdurrahman@apps.ipb.ac.id', 'kode' => 'H14'],
        ];

        \App\Models\Sakarsian::insert($data);
    }
}
